### ISSUE TITLE
ORCiDs for term editor values?

### ISSUE THREAD

**Issue by marijane** [data2health/credit-ontology#4]
_From @marijane on December 9, 2016 8:51_

I entered my name as a string in the term editor annotations, but I'm wondering whether it's appropriate to use an ORCiD as the value for this property.

_Copied from original issue: data2health/contributor-role-ontology#3_

**Comment by marijane** [comment]
_From @Public-Health-Bioinformatics on December 15, 2016 19:4_

You could see what the obo-discuss@lists.sourceforge.net list people think.  But I see the ORCID ids look like: orcid.org/0000-0002-8844-9165 .  It would be great if they had a "user handle" alternate id for the same entity, e.g. orcid.org/damion_dooley .

**Comment by marijane** [comment]
Part of the reason I have this question is that I recently read the OBO Tutorial, in which ORCIDs are used to identify investigators in data!  But you're right, asking the list is a good idea.

**Comment by marijane** [comment]
@mellybelly says yes!  ORCiDs

**Comment by nicolevasilevsky** [comment]
@marijane Should I go into the credit.owl file and update the term editor to your ORCID?

**Comment by nicolevasilevsky** [comment]
I updated the term editor annotation to MJ's ORCID.
closing this ticket
