### ISSUE TITLE
Include CASRAI IDs in class annotations

### ISSUE THREAD

**Issue by marijane** [data2health/credit-ontology#6]
_From @marijane on December 9, 2016 8:47_

Each of the CRediT Taxonomy roles has a unique ID in the CASRAI Dictionary.  We should include this ID in the annotations on the role classes, but it's not clear if there is an existing OBO annotation property that should be used for this.  The alternate term property does not seem quite right to me.

_Copied from original issue: data2health/contributor-role-ontology#1_

**Comment by marijane** [comment]
Melissa says use hasDBXref

**Comment by marijane** [comment]
See casrai dictionary here:
https://dictionary.casrai.org/Contributor_Roles

We want to add the "ID" as a dbxref

**Comment by nicolevasilevsky** [comment]
whenever I edit the ontology, it edits the catalog file as well, so I just committed that too (let me know if you'd prefer if I discarded that file)

**Comment by marijane** [comment]
I think that's fine for now, and thank you for letting me know.  There is [a known issue around this with the ODK](https://github.com/INCATools/ontology-development-kit/issues/105) but I don't think we need to worry about it unless we hit it.
